name: Repo_sync

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  
jobs:
  New-Update-Files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        pwd
        wget -O ./file/long https://raw.githubusercontent.com/hkpc/openit/main/long
        wget -O ./file/packages.sh https://raw.githubusercontent.com/djzng/packages/master/packages.sh
        wget -O ./file/kejilion.sh https://raw.githubusercontent.com/kejilion/sh/main/kejilion.sh   #科技lion一键脚本工具
        wget -O ./file/tool.sh https://raw.githubusercontent.com/woniu336/open_shell/main/tool.sh   #路飞工具箱
        wget -O ./file/worker.js https://raw.githubusercontent.com/bulianglin/psub/main/worker.js   #不良林的worker搭建永久免费的私人反代订阅转换服务代码
        wget -O ./file/InstallNET.sh https://raw.githubusercontent.com/MoeClub/Note/master/InstallNET.sh   #DD重装系统脚本
        git clone --depth=1 --branch=master https://github.com/ACL4SSR/ACL4SSR.git && cp -R ACL4SSR/Clash/config . && rm -rf ACL4SSR/
        
    - name: Commit
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m"action:`date`"
        git pull --rebase
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}        
